# Generated by Django 3.2.9 on 2021-11-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnCSS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='html',
            name='css_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='html',
            name='html_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='html',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
