# Generated by Django 3.2.9 on 2021-11-30 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learnCSS', '0002_auto_20211130_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='html',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='html',
            name='create_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='html',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
