# Generated by Django 3.2.9 on 2021-11-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnCSS', '0003_auto_20211130_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='html',
            name='author',
        ),
    ]
