# Generated by Django 3.2.9 on 2021-11-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnCSS', '0004_remove_html_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='html',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='html',
            name='modify_date',
        ),
    ]
