# Generated by Django 3.2.9 on 2021-11-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnCSS', '0004_alter_html_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='create_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
