# Generated by Django 3.2.9 on 2021-11-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnCSS', '0005_auto_20211130_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='html',
            old_name='css_content',
            new_name='css',
        ),
        migrations.RenameField(
            model_name='html',
            old_name='html_content',
            new_name='html',
        ),
        migrations.RenameField(
            model_name='html',
            old_name='title',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='html',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
