# Generated by Django 3.2.9 on 2021-11-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnCSS', '0006_auto_20211130_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
