# Generated by Django 3.2.9 on 2021-11-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnCSS', '0006_auto_20211201_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='html_answer',
            old_name='create_date',
            new_name='create_Date',
        ),
        migrations.RenameField(
            model_name='html_answer',
            old_name='modify_date',
            new_name='modify_Date',
        ),
    ]
