# Generated by Django 3.2.9 on 2021-11-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnCSS', '0007_alter_html_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
